// Mocks generated by Mockito 5.4.4 from annotations
// in gemchase_clean_arch/test/jewelry_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:gemchase_clean_arch/core/common/exports.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [JewelryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockJewelryUseCase extends _i1.Mock implements _i3.JewelryUseCase {
  @override
  _i4.Future<_i2.Either<_i3.Failure, List<_i3.JewelryEntity>>> getAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i3.Failure, List<_i3.JewelryEntity>>>.value(
                _FakeEither_0<_i3.Failure, List<_i3.JewelryEntity>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i3.Failure, List<_i3.JewelryEntity>>>.value(
                _FakeEither_0<_i3.Failure, List<_i3.JewelryEntity>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i3.Failure, List<_i3.JewelryEntity>>>);

  @override
  _i4.Future<_i2.Either<_i3.Failure, _i3.JewelryEntity>> getById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i3.Failure, _i3.JewelryEntity>>.value(
                _FakeEither_0<_i3.Failure, _i3.JewelryEntity>(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i3.Failure, _i3.JewelryEntity>>.value(
                _FakeEither_0<_i3.Failure, _i3.JewelryEntity>(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i3.Failure, _i3.JewelryEntity>>);
}
