name: gemchase_clean_arch
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

scripts:
  build_runner: flutter pub run build_runner build --delete-conflicting-outputs
  bundle: flutter build appbundle --flavor prod --dart-define=BASE_API_URL=https://hospitality-api.srotcloud.app/api/
  clean: flutter clean && flutter pub get && dart fix --apply

dependencies:
  awesome_dio_interceptor: ^1.2.0
  cached_network_image: ^3.4.0
  connectivity_plus: ^6.0.4
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.6.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.2
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  khalti: ^2.0.0
  khalti_flutter: ^3.0.0
  light: ^3.0.1
  local_auth: ^2.3.0
  mockito: ^5.4.4
  multi_select_flutter: ^4.1.3
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen: ^5.6.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
