// Mocks generated by Mockito 5.4.4 from annotations
// in gemchase_clean_arch/test/unit_test/jewelery_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:gemchase_clean_arch/core/failure/failure.dart' as _i6;
import 'package:gemchase_clean_arch/features/jewelery/domain/entity/jewelery_entity.dart'
    as _i7;
import 'package:gemchase_clean_arch/features/jewelery/domain/repository/jewelery_repository.dart'
    as _i2;
import 'package:gemchase_clean_arch/features/jewelery/domain/usecases/jewelery_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIJeweleryRepository_0 extends _i1.SmartFake
    implements _i2.IJeweleryRepository {
  _FakeIJeweleryRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [JeweleryUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockJeweleryUsecase extends _i1.Mock implements _i4.JeweleryUsecase {
  @override
  _i2.IJeweleryRepository get jeweleryRepository => (super.noSuchMethod(
        Invocation.getter(#jeweleryRepository),
        returnValue: _FakeIJeweleryRepository_0(
          this,
          Invocation.getter(#jeweleryRepository),
        ),
        returnValueForMissingStub: _FakeIJeweleryRepository_0(
          this,
          Invocation.getter(#jeweleryRepository),
        ),
      ) as _i2.IJeweleryRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.JeweleryEntity>>> getAllJewelerys(
          int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllJewelerys,
          [page],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.JeweleryEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.JeweleryEntity>>(
          this,
          Invocation.method(
            #getAllJewelerys,
            [page],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.JeweleryEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.JeweleryEntity>>(
          this,
          Invocation.method(
            #getAllJewelerys,
            [page],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.JeweleryEntity>>>);
}
